### ISSUE TITLE
tab组件，可以自定义选中tab的title颜色和底部滑块的颜色

### ISSUE THREAD

**Issue by hanf1990** [ant-design/ant-design-mini#578]
## 背景
 
tab组件，可以自定义选中tab的title颜色和底部滑块的颜色

## 期望
 
tab组件，可以自定义选中tab的title颜色和底部滑块的颜色

**Comment by jc9702507** [comment]
1. 添加一个props
2. 可以使用
```html
<tabs
  items="{{items}}"
  tabActiveClassName="custom"
/>
```

```css
.custom::after {
  background-color: red!important;
}
```
