### ISSUE TITLE
tabs 标签页 可以优化实现筛选功能吗?

### ISSUE THREAD

**Issue by lff2018** [ant-design/ant-design-mini#709]
## 背景
tabs 标签页 可以优化实现筛选功能吗?

## 期望
tabs  能实现切换图标的功能

## 思路
 
![f](https://user-images.githubusercontent.com/47960944/234497956-c1a9d234-a99c-4dfd-a170-9dffd5449205.png)

**Comment by jc9702507** [comment]
这个可以自己加上
![image](https://user-images.githubusercontent.com/113670357/234512651-0ee9d406-8c40-4c20-b146-524fa60312ae.png)


```html
<tabs items="{{items}}">
  <view slot="title" slot-scope="item">
    {{item.value.title}}
    <icon type="DownFill" class="icon" catchTap="catchTap" />
  </view>
</tabs>
```

```css
.icon {
  font-size: 12px;
  position: absolute;
  right: -4px;
  top: 12px;
  color: #333;
}
```
